name: tracker
services:
  - name: tracker
    environment_slug: docker
    envs:
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_NAME
        value: ${DB_NAME}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: ENCRYPTION_KEY
        value: ${ENCRYPTION_KEY}
      - key: API_KEY
        value: ${API_KEY}