environment:
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  API_KEY: "${API_KEY}"
packages:
  - name: tracker
    functions:
      - name: web
        main: "app:app"  # For example, if using uvicorn to run FastAPI app in app.py
        runtime: "python:3.10"
        web: true
        http_port: 8080
        routes:
          - path: "/"