name: location
services:
  - name: tracker
    web: true
    dockerfile_path: ./Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: "/"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      API_KEY: ${API_KEY}