environment:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  API_KEY: "${API_KEY}"
  DB_CA_CERT: "${DB_CA_CERT}"