environment:
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  API_KEY: "${API_KEY}"
packages:
  - name: tracker
    functions:
      - name: web
        main: "app:app"        # Points to your FastAPI app in app.py (FastAPI instance is named 'app')
        runtime: "python:3.10"  # Specify the runtime version
        web: true
        routes:
          - path: "/"