environment:
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  API_KEY: "${API_KEY}"
packages:
  - name: tracker
    functions:
      - name: web
        main: ""          # You can leave this empty if not needed
        runtime: "docker"
        dockerfile: "./Dockerfile"
        web: true
        http_port: 8080
        routes:
          - path: "/"