alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
spec_version: 1
services:
  - name: tracker
    instance_count: 1
    instance_size_slug: basic-xxs
    git:
      branch: main
      repo_clone_url: ${GIT_REPO_URL}
    dockerfile_path: ./Dockerfile
    http_port: 8080
    envs:
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_NAME
        value: ${DB_NAME}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: ENCRYPTION_KEY
        value: ${ENCRYPTION_KEY}
      - key: API_KEY
        value: ${API_KEY}