environment:
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  API_KEY: "${API_KEY}"

packages:
  - name: tracker
    actions:
      - name: app
        main: "app"
        runtime: "python:3.11"
        web: true